import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { request as httpRequest } from "node:http";
import {
  mkdir,
  mkdtemp,
  rm,
  symlink,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import test from "node:test";

import { createImageStudioServer } from "../server/server.mjs";

const PNG_BYTES = Buffer.from([137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 0]);
const ASSET_NAMES = [
  "source",
  "alpha",
  "foreground",
  "compositeBlack",
  "compositeWhite",
  "compositeSaturated",
];
const ASSET_FILES = {
  source: "source.png",
  alpha: "alpha.png",
  foreground: "foreground.png",
  compositeBlack: "composite-black.png",
  compositeWhite: "composite-white.png",
  compositeSaturated: "composite-saturated.png",
};

function makeCatalog() {
  const assetBase = "/research-assets/dev/calibration/MATTE-GT/fixture-01";
  const assets = Object.fromEntries(
    ASSET_NAMES.map((name) => [name, `${assetBase}/${ASSET_FILES[name]}`]),
  );
  return {
    schemaVersion: "review-catalog.v0",
    catalogId: "catalog-test",
    catalogVersion: "0.0.1",
    generatedAt: "2026-08-15T00:00:00.000Z",
    evidenceStatus: { level: "C1=0", purpose: "method-rehearsal" },
    visibilityPolicy: { allowed: ["public-synthetic"] },
    assetAllowlist: Object.values(assets).sort(),
    fixtures: [{
      id: "fixture-01",
      label: "Synthetic fixture 01",
      suite: "MATTE-GT",
      partition: "dev/calibration",
      sourceRevision: "generator-test@1",
      candidateAlias: "candidate-a",
      methodLabel: "synthetic ground truth",
      methodDetails: "Generated by the test-only deterministic fixture helper.",
      rightsRecordId: "rights.synthetic.test",
      visibility: "public-synthetic",
      evidenceStatus: { level: "C1=0", purpose: "method-rehearsal" },
      assets,
      facts: {
        category: "synthetic-shape",
        edgeType: "hard",
        expectedUse: "server contract test",
      },
    }],
  };
}

async function startResearchServer({
  catalog = makeCatalog(),
  previewMode = "local",
  writeCatalog = true,
} = {}) {
  const root = await mkdtemp(join(tmpdir(), "single-image-research-server-"));
  const webRoot = join(root, "web");
  const researchRoot = join(root, "research");
  const catalogPath = join(researchRoot, "manifests", "review-catalog.v0.json");
  await mkdir(webRoot, { recursive: true });
  await writeFile(join(webRoot, "index.html"), "<!doctype html><title>R0</title>");

  if (writeCatalog) {
    await mkdir(dirname(catalogPath), { recursive: true });
    await writeFile(catalogPath, JSON.stringify(catalog));
    for (const assetUrl of catalog.assetAllowlist ?? []) {
      if (typeof assetUrl !== "string" || !assetUrl.startsWith("/research-assets/")) continue;
      const target = join(
        researchRoot,
        "fixtures",
        ...assetUrl.slice("/research-assets/".length).split("/"),
      );
      await mkdir(dirname(target), { recursive: true });
      await writeFile(target, PNG_BYTES);
    }
  }

  const app = createImageStudioServer({
    apiKey: "",
    previewMode,
    webRoot,
    researchRoot,
    researchCatalogPath: catalogPath,
  });
  await new Promise((resolve, reject) => {
    app.server.once("error", reject);
    app.server.listen(0, "127.0.0.1", resolve);
  });
  const address = app.server.address();
  return {
    ...app,
    baseUrl: `http://127.0.0.1:${address.port}`,
    root,
    researchRoot,
    catalogPath,
    catalog,
    async close() {
      await new Promise((resolve, reject) => app.server.close((error) => error ? reject(error) : resolve()));
      await rm(root, { recursive: true, force: true });
    },
  };
}

async function responseJson(response) {
  return JSON.parse(await response.text());
}

async function rawRequest(origin, path, method = "GET") {
  const url = new URL(origin);
  return new Promise((resolve, reject) => {
    const request = httpRequest({
      hostname: url.hostname,
      port: url.port,
      path,
      method,
    }, (response) => {
      const chunks = [];
      response.on("data", (chunk) => chunks.push(chunk));
      response.on("end", () => resolve({
        status: response.statusCode,
        headers: response.headers,
        body: Buffer.concat(chunks),
      }));
    });
    request.on("error", reject);
    request.end();
  });
}

test("local preview serves the validated research catalog and allowlisted PNG", async (t) => {
  const app = await startResearchServer();
  t.after(() => app.close());

  const catalogResponse = await fetch(`${app.baseUrl}/api/research/fixtures`);
  assert.equal(catalogResponse.status, 200);
  assert.equal(catalogResponse.headers.get("cache-control"), "no-store");
  assert.equal(catalogResponse.headers.get("content-type"), "application/json; charset=utf-8");
  assert.deepEqual(await responseJson(catalogResponse), app.catalog);

  const assetUrl = app.catalog.fixtures[0].assets.source;
  const assetResponse = await fetch(`${app.baseUrl}${assetUrl}`);
  assert.equal(assetResponse.status, 200);
  assert.equal(assetResponse.headers.get("content-type"), "image/png");
  assert.equal(assetResponse.headers.get("cache-control"), "no-store");
  assert.equal(assetResponse.headers.get("x-content-type-options"), "nosniff");
  assert.deepEqual(Buffer.from(await assetResponse.arrayBuffer()), PNG_BYTES);
});

test("local preview serves a valid empty research catalog with HTTP 200", async (t) => {
  const catalog = makeCatalog();
  catalog.fixtures = [];
  catalog.assetAllowlist = [];
  const app = await startResearchServer({ catalog });
  t.after(() => app.close());

  const response = await fetch(`${app.baseUrl}/api/research/fixtures`);
  assert.equal(response.status, 200);
  assert.equal(response.headers.get("cache-control"), "no-store");
  assert.deepEqual(await responseJson(response), catalog);
});

test("research PNG supports HEAD without returning a response body", async (t) => {
  const app = await startResearchServer();
  t.after(() => app.close());

  const assetUrl = app.catalog.fixtures[0].assets.alpha;
  const response = await fetch(`${app.baseUrl}${assetUrl}`, { method: "HEAD" });
  assert.equal(response.status, 200);
  assert.equal(response.headers.get("content-type"), "image/png");
  assert.equal(response.headers.get("cache-control"), "no-store");
  assert.equal(Number(response.headers.get("content-length")), PNG_BYTES.length);
  assert.equal((await response.arrayBuffer()).byteLength, 0);
});

test("LAN rejects research catalog and assets before reading the catalog", async (t) => {
  const app = await startResearchServer({ previewMode: "lan", writeCatalog: false });
  t.after(() => app.close());

  const catalogResponse = await fetch(`${app.baseUrl}/api/research/fixtures`);
  assert.equal(catalogResponse.status, 403);
  assert.equal((await responseJson(catalogResponse)).error.code, "lan_research_disabled");

  const assetResponse = await fetch(
    `${app.baseUrl}/research-assets/dev/calibration/MATTE-GT/missing/source.png`,
    { method: "HEAD" },
  );
  assert.equal(assetResponse.status, 403);
  assert.equal(assetResponse.headers.get("content-type"), "application/json; charset=utf-8");
});

test("research routes reject unsupported methods", async (t) => {
  const app = await startResearchServer();
  t.after(() => app.close());

  const catalogResponse = await fetch(`${app.baseUrl}/api/research/fixtures`, { method: "POST" });
  assert.equal(catalogResponse.status, 405);
  assert.equal((await responseJson(catalogResponse)).error.code, "method_not_allowed");

  const assetResponse = await fetch(`${app.baseUrl}${app.catalog.fixtures[0].assets.source}`, {
    method: "POST",
  });
  assert.equal(assetResponse.status, 405);
  assert.equal((await responseJson(assetResponse)).error.code, "method_not_allowed");
});

test("research asset route rejects traversal and non-PNG or directory targets", async (t) => {
  const app = await startResearchServer();
  t.after(() => app.close());

  for (const path of [
    "/research-assets/../secret.png",
    "/research-assets/%2e%2e%2fsecret.png",
    "/research-assets/dev%5csecret.png",
    "/research-assets/dev/calibration/readme.txt",
    "/research-assets/dev/calibration/",
  ]) {
    const response = await rawRequest(app.baseUrl, path);
    assert.equal(response.status, 403, path);
    assert.equal(JSON.parse(response.body).error.code, "research_asset_forbidden", path);
  }
});

test("research asset route hides unlisted, missing, and directory targets", async (t) => {
  const app = await startResearchServer();
  t.after(() => app.close());

  const unlistedPath = join(app.researchRoot, "fixtures", "unlisted.png");
  await writeFile(unlistedPath, PNG_BYTES);
  const unlisted = await fetch(`${app.baseUrl}/research-assets/unlisted.png`);
  assert.equal(unlisted.status, 404);
  assert.equal((await responseJson(unlisted)).error.code, "research_asset_not_found");

  const missingUrl = app.catalog.fixtures[0].assets.foreground;
  const missingPath = join(
    app.researchRoot,
    "fixtures",
    ...missingUrl.slice("/research-assets/".length).split("/"),
  );
  await rm(missingPath);
  const missing = await fetch(`${app.baseUrl}${missingUrl}`);
  assert.equal(missing.status, 404);
  assert.equal((await responseJson(missing)).error.code, "research_asset_not_found");

  const directoryUrl = app.catalog.fixtures[0].assets.compositeBlack;
  const directoryPath = join(
    app.researchRoot,
    "fixtures",
    ...directoryUrl.slice("/research-assets/".length).split("/"),
  );
  await rm(directoryPath);
  await mkdir(directoryPath);
  const directory = await fetch(`${app.baseUrl}${directoryUrl}`);
  assert.equal(directory.status, 404);
  assert.equal((await responseJson(directory)).error.code, "research_asset_not_found");
});

test("research asset route rejects an allowlisted symlink that escapes fixtures", async (t) => {
  const app = await startResearchServer();
  t.after(() => app.close());

  const assetUrl = app.catalog.fixtures[0].assets.source;
  const assetPath = join(
    app.researchRoot,
    "fixtures",
    ...assetUrl.slice("/research-assets/".length).split("/"),
  );
  const outsidePath = join(app.root, `outside-${randomUUID()}.png`);
  await writeFile(outsidePath, PNG_BYTES);
  await rm(assetPath);
  try {
    await symlink(outsidePath, assetPath, "file");
  } catch (error) {
    if (error?.code === "EPERM" || error?.code === "EACCES") {
      const fixtureDirectory = dirname(assetPath);
      const outsideDirectory = join(app.root, `outside-${randomUUID()}`);
      await mkdir(outsideDirectory);
      await writeFile(join(outsideDirectory, "source.png"), PNG_BYTES);
      await rm(fixtureDirectory, { recursive: true, force: true });
      try {
        await symlink(outsideDirectory, fixtureDirectory, "junction");
      } catch (junctionError) {
        if (junctionError?.code === "EPERM" || junctionError?.code === "EACCES") {
          t.skip("This environment does not permit creating a symlink or junction");
          return;
        }
        throw junctionError;
      }
    } else {
      throw error;
    }
  }

  const response = await fetch(`${app.baseUrl}${assetUrl}`);
  assert.equal(response.status, 403);
  assert.equal((await responseJson(response)).error.code, "research_asset_forbidden");
});

test("missing and invalid research catalogs share a non-disclosing error", async (t) => {
  const missingApp = await startResearchServer({ writeCatalog: false });
  t.after(() => missingApp.close());
  const missing = await fetch(`${missingApp.baseUrl}/api/research/fixtures`);
  assert.equal(missing.status, 503);
  const missingBody = await responseJson(missing);
  assert.deepEqual(missingBody.error, {
    code: "research_catalog_unavailable",
    message: "研究夹具清单不可用",
    requestId: null,
  });
  assert.equal(JSON.stringify(missingBody).includes(missingApp.root), false);

  const invalidApp = await startResearchServer();
  t.after(() => invalidApp.close());
  await writeFile(invalidApp.catalogPath, "{invalid-json");
  const invalid = await fetch(`${invalidApp.baseUrl}/api/research/fixtures`);
  assert.equal(invalid.status, 503);
  assert.deepEqual((await responseJson(invalid)).error, missingBody.error);
});

test("catalog validation fails closed on visibility, unknown fields, or allowlist mismatch", async () => {
  const privateCatalog = makeCatalog();
  privateCatalog.fixtures[0].visibility = "private-user";

  const unknownFieldCatalog = makeCatalog();
  unknownFieldCatalog.unexpected = true;

  const mismatchedCatalog = makeCatalog();
  mismatchedCatalog.assetAllowlist.push(
    "/research-assets/dev/calibration/MATTE-GT/fixture-01/unreferenced.png",
  );
  mismatchedCatalog.assetAllowlist.sort();

  const emptyFixturesWithAssets = makeCatalog();
  emptyFixturesWithAssets.fixtures = [];

  const fixturesWithoutAssets = makeCatalog();
  fixturesWithoutAssets.assetAllowlist = [];

  for (const catalog of [
    privateCatalog,
    unknownFieldCatalog,
    mismatchedCatalog,
    emptyFixturesWithAssets,
    fixturesWithoutAssets,
  ]) {
    const app = await startResearchServer({ catalog });
    try {
      const response = await fetch(`${app.baseUrl}/api/research/fixtures`);
      assert.equal(response.status, 503);
      assert.equal((await responseJson(response)).error.code, "research_catalog_unavailable");
    } finally {
      await app.close();
    }
  }
});
